### ISSUE TITLE
Import error?

### ISSUE THREAD

**Issue by Almenon** [ppb/pursuedpybear#162]
W/ Windows 10 python 3.5 I tried importing ppb

```python
import ppb
```

But I got the following error:

```
Traceback (most recent call last):
  line 1, in <module>
  File "C:\Users\Almenon\AppData\Roaming\Python\Python35\site-packages\ppb\__init__.py", line 2, in <module>
    from ppb.engine import GameEngine
  File "C:\Users\Almenon\AppData\Roaming\Python\Python35\site-packages\ppb\engine.py", line 7, in <module>
    from typing import Type
ImportError: cannot import name 'Type'
```

**Comment by pathunstrom** [comment]
@Almenon Thanks for the report. We do not guarantee that `ppb` works with Python 3.5. That said, that error seems very strange. Which bugfix release of Python are you on?

**Comment by Almenon** [comment]
3.5.0

I just looked up the error and it sounds like it is because I'm using python 3.5

I'll upgrade to 3.6 and report back :)

**Comment by Almenon** [comment]
also if you want to talk about it I'm in the hall
